parameters:
    csbill_payment.menu.top.class: CSBill\PaymentBundle\Menu\PaymentsMenu

services:
    csbill_payment.menu.top:
        class: %csbill_payment.menu.top.class%
        tags:
            - { name: cs_core.menu, menu: top_right, method: topMenu }
