parameters:
    csbill_payment.menu.top.class: CSBill\PaymentBundle\Menu\PaymentsMenu
    csbill.payment.payum.paypal_express.action.capture_order.class: CSBill\PaymentBundle\Action\PaypalExpress\CaptureOrderAction
    csbill.payment.event.subscriber.class: CSBill\PaymentBundle\Listener\PaymentSubscriber

services:
    csbill_payment.menu.top:
        class: %csbill_payment.menu.top.class%
        tags:
            - { name: cs_core.menu, menu: top_right, method: topMenu }

    csbill_payment.method.manager:
        class: CSBill\PaymentBundle\Manager\PaymentMethodManager
        arguments: [@payum]

    csbill.payment.payum.paypal_express.action.capture_order_action:
        class: %csbill.payment.payum.paypal_express.action.capture_order.class%
        arguments: [@payum.security.token_factory, %currency%]

    csbill.payment.payum.paypal_express_checkout_api:
        class: Payum\Paypal\ExpressCheckout\Nvp\Api
        arguments:
            - @payum.buzz.client
            - @=service("csbill.payment.method.options").get('paypal_express_checkout')

    csbill.payment.method.options:
        class: CSBill\PaymentBundle\Manager\PaymentSettingsManager
        arguments: [@doctrine]

    csbill.payment.event.subscriber:
        class: %csbill.payment.event.subscriber.class%
        arguments: [@invoice.manager]
        tags:
            - { name: kernel.event_subscriber }
