parameters:
    csbill_invoice.menu.class: CSBill\InvoiceBundle\Menu\Main
    csbill_invoice.manager.class: CSBill\InvoiceBundle\Manager\InvoiceManager

services:
    csbill_invoice.menu:
        class: %csbill_invoice.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: invoices_index,  method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_view,   method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_create, method: invoicesMenu }
            - { name: cs_core.menu, menu: invoices_edit, method: invoicesMenu }

    invoice.manager:
        class: %csbill_invoice.manager.class%
        arguments: [@doctrine]
        calls:
            - [ setContainer, [@service_container]]